/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ECG.ecgDrawPanel;
import javax.swing.JPanel;
import javax.swing.SwingWorker;

/**
 *
 * @author Ahmed
 */
public class EditPatientPanel extends JPanel {

    ecgDrawPanel ecgPanel;
    boolean isOnScreen = false;

    /**
     * Creates new form EditPatient
     */
    public EditPatientPanel() {
        ecgPanel = new ecgDrawPanel();
        initComponents();
        this.add(ecgPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setOnScreenFlag() {
        this.isOnScreen = true;
        this.displayChart();
    }

    public void setNotOnScreenFlag() {
        this.isOnScreen = false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void displayChart() {
        SwingWorker theWorker = new SwingWorker() {

            @Override
            protected Object doInBackground() throws Exception {
                ecgPanel.move_1();
                return null;
            }
        };

        if (!this.isOnScreen) {
            //ecgPanel.move_1();
            theWorker.cancel(true);
        }else{
            theWorker.execute();
        }

    }
}
